name: media_picker_manager
description: A highly configurable Flutter media picker and manager for local and remote images, videos and files.
version: 0.1.1
homepage: https://github.com/mustafaLzoghby/media_picker_manager
repository: https://github.com/mustafaLzoghby/media_picker_manager
issue_tracker: https://github.com/mustafaLzoghby/media_picker_manager/issues

topics:
  - media-picker
  - image-picker
  - video-picker
  - file-picker
  - upload

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.3
  file_picker: ^12.1.0
  cross_file: ^0.3.5+4
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
